name = "kieran-app"
compatibility_date = "2025-11-23"
pages_build_output_dir = "dist"

[images]
binding = "IMAGES"

[[r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "kieran-images"

[[d1_databases]]
binding = "DB"
database_name = "kieran-db"
database_id = "2b58cfa4-5f85-424b-8643-bc440a177f82"
